name: Run Python Script on Cron Schedule to Sync OpCodes

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout moewcorp/FFXIVNetworkOpcodes repository
        uses: actions/checkout@v4
        with:
          repository: 'moewcorp/FFXIVNetworkOpcodes'
          token: ${{ secrets.GITHUB_TOKEN }}
          path: 'FFXIVNetworkOpcodes'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Run Cron Task
        run: python ${{ github.workspace }}/utils/CronTask.py ${{ github.workspace }}/FFXIVNetworkOpcodes/output ${{ github.workspace }}/opcodes.json

      - name: Remove moewcorp/FFXIVNetworkOpcodes
        run: rm -rf FFXIVNetworkOpcodes

      - uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Action
          author_email: github-actions[bot]@users.noreply.github.com
          message: Regenerate OpCodes.json

