name: Run Python Script on Cron Schedule to Sync OpCodes

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout moewcorp/FFXIVNetworkOpcodes repository
        uses: actions/checkout@v4
        with:
          repository: 'moewcorp/FFXIVNetworkOpcodes'  # 另一个仓库的用户名/仓库名
          token: ${{ secrets.GITHUB_TOKEN }}
          path: 'FFXIVNetworkOpcodes'

      - run: ls FFXIVNetworkOpcodes/output

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # 选择 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

